name: Deploy to Vercel

on:
  push:
    branches:
      - main   # change this if your production branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Deploy Hook
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
